### PR TITLE
Added the use of environment variables for running parameters

### PR DESCRIPTION
**Pull request by dj21d**
I wanted to be able to customize the variables in your code without the need to edit the working code. The code will look for environmental variables if they don't exist default back to your set variables

### CODE REVIEW

**Comment by coderofsalvation** [comment]
merged. Thx.
Btw. also thanks for updating the README.md, this is a very good habit when doing PR's.

**Comment by coderofsalvation** [comment]
btw. do you want maintainer permissions? Right now this is a dictatorrepo with only one maintainer (me).

**Comment by dj21d** [comment]
Sure, I would appreciate it. Would you be able to update the version and npm?

**Comment by coderofsalvation** [comment]
ok done.

**Pull request merged**
